#!/usr/bin/env sh

# bar
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "PragmataPro:Bold:12.0"
yabai -m config status_bar_icon_font         "PragmataPro:Regular:16.0"
yabai -m config status_bar_background_color  0xff0b0b0b
yabai -m config status_bar_foreground_color  0xffb5b5b5
yabai -m config status_bar_space_icon_strip          
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.62
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# space
yabai -m config layout                       bsp
yabai -m config top_padding                  40
yabai -m config bottom_padding               40
yabai -m config left_padding                 40
yabai -m config right_padding                40
yabai -m config window_gap                   20

# window rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Xcode$" manage=off
yabai -m rule --add app="^Gemini 2$" manage=off
yabai -m rule --add app="^Adobe Photoshop 2020$" manage=off

echo "yabai configuration loaded.."
