#!/usr/bin/env bash

# Install command-line tools
xcode select --install

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
echo Don’t forget to add '$(brew --prefix coreutils)/libexec/gnubin' to '$PATH'
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`
brew install gnu-sed
# Install Zsh
brew install zsh
# Switch to using brew-installed bash as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/zsh" /etc/shells; then
    echo "${BREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells
    chsh -s "${BREW_PREFIX}/bin/zsh"
fi

# tap into repositories
brew tap "cartr/qt4"
brew tap "cjbassi/gotop"
brew tap "eddieantonio/eddieantonio"
brew tap "getsentry/tools"
brew tap "homebrew install/bundle"
brew tap "homebrew install/brew install --cask"
brew tap "homebrew install/brew install --cask-drivers"
brew tap "homebrew install/brew install --cask-versions"
brew tap "homebrew install/core"
brew tap "homebrew install/services"
brew tap "ivandokov/contrib"
brew tap "khanhas/brew tap"
brew tap "koekeishiya/formulae"
brew tap "mopidy/mopidy"
brew tap "osx-cross/avr"
brew tap "pr0d1r2/python2"
brew tap "romkatv/powerlevel10k"

# brew some packages
brew install "adns"
brew install "oniguruma"
brew install "jq"
brew install "ansiweather"
brew install "openjdk"
brew install "ant"
brew install "aom"
brew install "apr"
brew install "openssl@1.1"
brew install "apr-util"
brew install "aptly"
brew install "argon2"
brew install "libssh2"
brew install "aria2"
brew install "eigen"
brew install "gmp"
brew install "isl"
brew install "mpfr"
brew install "libmpc"
brew install "gcc"
brew install "hwloc"
brew install "libevent"
brew install "open-mpi"
brew install "openblas"
brew install "arpack"
brew install "szip"
brew install "hdf5"
brew install "superlu"
brew install "armadillo"
brew install "asciidoctor"
brew install "asio"
brew install "aspell"
brew install "astyle"
brew install "gdbm"
brew install "gettext"
brew install "libffi"
brew install "pcre"
brew install "readline"
brew install "sqlite"
brew install "xz"
brew install "python@3.9"
brew install "glib"
brew install "atk"
brew install "autoconf"
brew install "automake"
brew install "libelf"
brew install "libusb"
brew install "libusb-compat"
brew install "libftdi0"
brew install "libhid"
brew install "avrdude"
brew install "bash"
brew install "bash-completion"
brew install "bat"
brew install "bdw-gc"
brew install "bison"
brew install "libtool"
brew install "libunistring"
brew install "pkg-config"
brew install "guile"
brew install "libidn2"
brew install "libtasn1"
brew install "nettle"
brew install "p11-kit"
brew install "unbound"
brew install "gnutls"
brew install "libgpg-error"
brew install "libgcrypt"
brew install "bitlbee"
brew install "blueutil"
brew install "icu4c"
brew install "boost"
brew install "botan"
brew install "brotli"
brew install "byacc"
brew install "bzip2"
brew install "c-ares"
brew install "libpng"
brew install "freetype"
brew install "fontconfig"
brew install "lzo"
brew install "pixman"
brew install "cairo"
brew install "carthage"
brew install "llvm"
brew install "castxml"
brew install "zstd"
brew install "ccache"
brew install "cmake"
brew install "gflags"
brew install "glog"
brew install "metis"
brew install "tbb"
brew install "suite-sparse"
brew install "ceres-solver"
brew install "cfitsio"
brew install "cgal"
brew install "cmatrix"
brew install "cminpack"
brew install "coreutils"
brew install "cppunit"
brew install "curl"
brew install "jansson"
brew install "jemalloc"
brew install "libev"
brew install "libidn"
brew install "libmetalink"
brew install "nghttp2"
brew install "openldap"
brew install "rtmpdump"
brew install "curl-openssl"
brew install "cython"
brew install "dav1d"
brew install "dbus"
brew install "jpeg"
brew install "libtiff"
brew install "dcmtk"
brew install "jasper"
brew install "little-cms2"
brew install "dcraw"
brew install "desktop-file-utils"
brew install "dfu-programmer"
brew install "diffutils"
brew install "djvulibre"
brew install "docbook"
brew install "docbook-xsl"
brew install "double-conversion"
brew install "doxygen"
brew install "emacs"
brew install "popt"
brew install "epsilon"
brew install "node"
brew install "eslint"
brew install "exa"
brew install "sdl"
brew install "libagg"
brew install "exact-image"
brew install "exiftool"
brew install "libssh"
brew install "exiv2"
brew install "expat"
brew install "faac"
brew install "faad2"
brew install "fcgi"
brew install "fd"
brew install "fdk-aac"
brew install "fff"
brew install "libogg"
brew install "flac"
brew install "frei0r"
brew install "fribidi"
brew install "giflib"
brew install "gobject-introspection"
brew install "graphite2"
brew install "harfbuzz"
brew install "lame"
brew install "openjpeg"
brew install "webp"
brew install "leptonica"
brew install "libass"
brew install "libbluray"
brew install "libvorbis"
brew install "opus"
brew install "libsndfile"
brew install "libsamplerate"
brew install "libsoxr"
brew install "libvidstab"
brew install "libvpx"
brew install "opencore-amr"
brew install "rav1e"
brew install "rubberband"
brew install "sdl2"
brew install "snappy"
brew install "speex"
brew install "srt"
brew install "tesseract"
brew install "theora"
brew install "x264"
brew install "x265"
brew install "xvid"
brew install "ffmpeg"
brew install "libkate"
brew install "ffmpeg2theora"
brew install "fftw"
brew install "findutils"
brew install "flake8"
brew install "flann"
brew install "flex"
brew install "portaudio"
brew install "fluid-synth"
brew install "freeimage"
brew install "unixodbc"
brew install "freetds"
brew install "freexl"
brew install "fzf"
brew install "gawk"
brew install "gd"
brew install "geos"
brew install "json-c"
brew install "krb5"
brew install "libxml2"
brew install "libdap"
brew install "libpq"
brew install "netcdf"
brew install "nspr"
brew install "nss"
brew install "numpy"
brew install "qt"
brew install "poppler"
brew install "xerces-c"
brew install "gdal"
brew install "gdb"
brew install "gdk-pixbuf"
brew install "geoip"
brew install "ghostscript"
brew install "pcre2"
brew install "git"
brew install "git-lfs"
brew install "gl2ps"
brew install "glew"
brew install "glfw"
brew install "gsettings-desktop-schemas"
brew install "glib-networking"
brew install "gnu-getopt"
brew install "gnu-sed"
brew install "gnu-tar"
brew install "libassuan"
brew install "libksba"
brew install "npth"
brew install "pinentry"
brew install "gnupg"
brew install "libcerf"
brew install "lua"
brew install "pango"
brew install "gnuplot"
brew install "go"
brew install "gperf"
brew install "libgphoto2"
brew install "gphoto2"
brew install "shapelib"
brew install "gpsbabel"
brew install "gptfdisk"
brew install "gradle"
brew install "graphene"
brew install "netpbm"
brew install "gts"
brew install "graphviz"
brew install "grep"
brew install "gsl"
brew install "gstreamer"
brew install "orc"
brew install "gst-plugins-base"
brew install "libcuefile"
brew install "libmms"
brew install "libnice"
brew install "libreplaygain"
brew install "libusrsctp"
brew install "musepack"
brew install "srtp"
brew install "gst-plugins-bad"
brew install "hicolor-icon-theme"
brew install "libepoxy"
brew install "gtk+3"
brew install "libpsl"
brew install "libshout"
brew install "vala"
brew install "libsoup"
brew install "taglib"
brew install "gst-plugins-good"
brew install "gst-plugins-ugly"
brew install "py3cairo"
brew install "pygobject3"
brew install "gst-python"
brew install "gtk+"
brew install "gtkglext"
brew install "gulp-cli"
brew install "handbrake"
brew install "help2man"
brew install "hexyl"
brew install "highlight"
brew install "ncurses"
brew install "htop"
brew install "ifstat"
brew install "ilmbase"
brew install "libde265"
brew install "xmlto"
brew install "shared-mime-info"
brew install "libheif"
brew install "liblqr"
brew install "libomp"
brew install "openexr"
brew install "imagemagick"
brew install "inetutils"
brew install "jpeg-turbo"
brew install "json-glib"
brew install "jsoncpp"
brew install "lapack"
brew install "laszip"
brew install "lbzip2"
brew install "libao"
brew install "libb2"
brew install "lz4"
brew install "libarchive"
brew install "libav", link: false
brew install "libcroco"
brew install "libexif"
brew install "libglade"
brew install "libharu"
brew install "libiconv"
brew install "libid3tag"
brew install "libmaxminddb"
brew install "libmpdclient"
brew install "libnfs"
brew install "libpcap"
brew install "librsvg"
brew install "libsass"
brew install "libscrypt"
brew install "libsodium"
brew install "libsvg"
brew install "libsvg-cairo"
brew install "libsvm"
brew install "unibilium"
brew install "libtermkey"
brew install "libupnp"
brew install "libuv"
brew install "libvterm"
brew install "libxslt"
brew install "libyaml"
brew install "libzip"
brew install "lighttpd"
brew install "lolcat"
brew install "lua@5.1"
brew install "luajit"
brew install "lunchy"
brew install "lynx"
brew install "m-cli"
brew install "mad"
brew install "mas"
brew install "mdbtools"
brew install "ninja"
brew install "meson"
brew install "minizip"
brew install "mono"
brew install "moreutils"
brew install "mpc"
brew install "mpd"
brew install "mujs"
brew install "uchardet"
brew install "zimg"
brew install "vapoursynth"
brew install "youtube-dl"
brew install "mpv"
brew install "msgpack"
brew install "muparser"
brew install "mupdf-tools"
brew install "protobuf"
brew install "mysql"
brew install "mysql-client"
brew install "mysql@5.7"
brew install "nasm"
brew install "ncmpcpp"
brew install "screenresolution"
brew install "neofetch"
brew install "neovim"
brew install "netcat"
brew install "nmap"
brew install "redis"
brew install "rrdtool"
brew install "ntopng"
brew install "sip"
brew install "pyqt"
brew install "vtk"
brew install "opencv"
brew install "openslide"
brew install "pkcs11-helper"
brew install "openvpn"
brew install "opusfile"
brew install "p7zip"
brew install "pegtl"
brew install "perl"
brew install "tidy-html5"
brew install "php"
brew install "pidof"
brew install "pipes-sh"
brew install "podofo"
brew install "potrace"
brew install "prettier"
brew install "protobuf-c"
brew install "pth"
brew install "pugixml"
brew install "pulseaudio"
brew install "pv"
brew install "py2cairo"
brew install "pybind11"
brew install "pylint"
brew install "pyside"
brew install "qca"
brew install "qhull"
brew install "qjson"
brew install "quilt"
brew install "qwt"
brew install "qwtpolar"
brew install "r"
brew install "redshift"
brew install "regex-opt"
brew install "rmtrash"
brew install "xxhash"
brew install "rsync"
brew install "ruby"
brew install "sassc"
brew install "scipy"
brew install "sfcgal"
brew install "shfmt"
brew install "sleepwatcher"
brew install "sox"
brew install "spatialindex"
brew install "spawn-fcgi"
brew install "sphinx"
brew install "utf8proc"
brew install "subversion"
brew install "svg2pdf"
brew install "swig"
brew install "tcl-tk"
brew install "terminal-notifier"
brew install "tesseract-lang"
brew install "texinfo"
brew install "tinyxml"
brew install "tmux"
brew install "tor"
brew install "torsocks"
brew install "tree"
brew install "twine-pypi"
brew install "ufraw"
brew install "utimer"
brew install "v8"
brew install "vim"
brew install "watchman"
brew install "watson"
brew install "weechat"
brew install "wget"
brew install "wxmac"
brew install "wxpython"
brew install "yarn"
brew install "yasm"
brew install "you-get"
brew install "zlib"
brew install "zsh"
brew install "cartr/qt4/openssl@1.0"
brew install "cartr/qt4/qt@4"
brew install "cartr/qt4/qt-webkit@2.3"
brew install "cjbassi/gotop/gotop"
brew install "eddieantonio/eddieantonio/imgcat"
brew install "getsentry/tools/sentry-cli"
brew install "khanhas/brew tap/spicetify-cli"
brew install "koekeishiya/formulae/skhd"
brew install "koekeishiya/formulae/yabai"
brew install "osx-cross/avr/avr-gcc"
brew install "pr0d1r2/python2/python@2.7.17"
brew install "romkatv/powerlevel10k/powerlevel10k"

# brew some casks
brew install --cask "arduino"
brew install --cask "google-chrome"
brew install --cask "iterm2"
brew install --cask "logitech-options"
brew install --cask "mono-mdk"
brew install --cask "phantomjs"
brew install --cask "qlcolorcode"
brew install --cask "qlimagesize"
brew install --cask "qlmarkdown"
brew install --cask "qlstephen"
brew install --cask "qlvideo"
brew install --cask "qmk-toolbox"
brew install --cask "qt-creator"
brew install --cask "quicklook-json"
brew install --cask "quicklookase"
brew install --cask "rar"
brew install --cask "sonarr-beta"
brew install --cask "sublime-text"
brew install --cask "the-unarchiver"
brew install --cask "transmission"
brew install --cask "ubersicht"
brew install --cask "xquartz"

# mopidy
brew tap mopidy/mopidy
brew install "mopidy/mopidy/mopidy"
brew install "mopidy/mopidy/mopidy-local"
brew install "mopidy/mopidy/mopidy-mpd"
brew install "mopidy/mopidy/libspotify"
brew install "mopidy/mopidy/pyspotify"
brew install "mopidy/mopidy/mopidy-spotify"
brew install "mopidy/mopidy/mopidy-podcast"
brew install "mopidy/mopidy/mopidy-podcast-itunes"

# update & cleanup
brew update
brew upgrade
brew cleanup
brew cleanup -s

# install node packages
#curl -sL install-node.now.sh/lts | bash
brew install yarn
npm install -g bullshit-generator
npm install -g capture-website-cli
npm install -g cjsx-codemod
npm install -g clean-css-cli
npm install -g csscleanerpro
npm install -g csslint
npm install -g gtop
npm install -g icon-gen
npm install -g idea
npm install -g install-peerdeps
npm install -g js2coffee
npm install -g less
npm install -g milligram-cli
npm install -g node-cipher
npm install -g npm
npm install -g npm-install-peers
npm install -g organize-cli
npm install -g pageres
npm install -g pageres-cli
npm install -g pdf2image
npm install -g pdf2images
npm install -g peerflix
npm install -g postcss-cli
npm install -g postcss-sorting
npm install -g purify-css
npm install -g sass
npm install -g stylelint
npm install -g vsce
